apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.16.1
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.16.1
    releaseName: istiod
    namespace: istio-system
    includeCRDs: true