apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - namespace-external.yaml

patchesStrategicMerge:
  - cmd-params.yaml
  - server-params.yaml