apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  # Build options/parameters to use with `kustomize build` (optional)
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm