apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  generated-by: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: Service
      name: mountebank-svc
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-server
      - op: add
        path: /spec/selector/app
        value: mountebank-server
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: mountebank-deploy
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-server
      - op: add
        path: /spec/selector/matchLabels/app
        value: mountebank-server
      - op: add
        path: /spec/template/metadata/labels/app
        value: mountebank-server