apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  generated-by: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - sealed-secrets.yaml

patches:
  - target:
      kind: ConfigMap
      version: v1
      name: api-mountebank-cm
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-api
  - target:
      kind: Service
      version: v1
      name: main-svc-mountebank
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-api
      - op: add
        path: /spec/selector/app
        value: mountebank-api
  - target:
      kind: Deployment
      group: apps
      version: v1
      name: api-mountebank-deploy
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-api
      - op: add
        path: /spec/template/metadata/labels/app
        value: mountebank-api
      - op: add
        path: /spec/selector/matchLabels/app
        value: mountebank-api
  - target:
      kind: Ingress
      version: v1
      group: networking.k8s.io
      name: contour-ingress
    patch: |-
      - op: add
        path: /metadata/labels/app
        value: mountebank-api