apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-mountebank-secret
  namespace: mountebank
spec:
  encryptedData:
    secrets.toml: AgBEsZcqhlZOf4WjKJGQ1QYGWrrUu/CG+dO5lvl2fXhqn0vGG+4mkh3xrRYxXqMI2vXifQ7rm6cVoxbF07oBnxGwJ3+xPkM/zpAC0vnOX4PAGoPbXG848ZQ/eFm28RHdCk8riAUN4g9IbdyIXw2/WVXufrq5ANdf9eAxrUUiu6XlbW0gU8gywgML/MCtv0qvq1EJLVyGv9TNjq7FBELzjxBX9qO8PdokFkKy0YCBDDJTnN56kxnNiuw1WSV4ihoH78kvi9MRUQQlDDeSAGDCZb3UAlfv3ytN/e6hUH0fQzzvJk2Hty+i/PZ0ODPtJke/LDCg9sNtWEGWb4XuzZX0h4hVBDKONPzIMzBZmIBBdcBvAEbBRhkuerZCUCw+x2Kw46VPkcZMBKDfsSiXRP/ckKkALRBYby0zefpSP+z+bH3O9CUDASFwRF9IFVn4YLkLxyqhQpqAwltFvDSM8uhxpRlaAbrpDeSq9WgeHgHYV7Eukl0wocAhqKicm/UvrNmZO7W7Yztn8KsjS+JBQlPTFamG3igAS2NMCx6b1W5GQ12YAgt0x3CacgAWKO2Qsk1/YZs3s2Fwv1Wer3QJIIFXcqs8CnxtQ1YVvthsNbY89yGMOcD6BfJ+QymwGw4USIEFta5NyNHbbOy2gUIvQMnzmNrDpinI6m3ClIz7lShGcWM7Ki6zzRTyOWytpC9++MF3fwGKe/7KlQ7E7zMR/qCy/0YtL1AplYc+asYZ6r7pn3/uE1G1UHt7PSYaCfSDInYhZksMWC125DU6shuE5pCCNtgUNZVvSj0m7TA31CtbVBRz9jSZldGPJXgvn/ioQiFa5mmJH5Hq9pe1OI6WcFGEoVSFYVxAxwWm/ULbXDlyt3bJbvHOgcuVVGGW/4UQWmotPMU/l5ycnVTzOE8e+tyzewOTgF/ENapRQOjZQEbUG4eWbUfeWyZzxZPTJneUh+t2CQcKcVFa0zDMvziXGQu49iHwm1rO63bnYHDY08hPDBo4G7dK+LNRN439KJtM5afqc6GwprRq2xCKjKM5T2AevWhooxuRVnEK0Yw7QHgzYfdgym0Yr3O+j3HuFlP/5Bz3fH2AHP8TRlfQBGxq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mountebank-api
        name: api-mountebank-secret
        version: 0.1.0
      name: api-mountebank-secret
      namespace: mountebank

