apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-mountebank-secret
  namespace: mountebank
spec:
  encryptedData:
    secrets.toml: AgBOQx70wPENESjF41zlYer94q0rCc5v9mo/jsrhFltSjJ43w2Z6hv3BL0KDKPuct7sx+4uGN2JHR/f33Si+yZIrOVI7FweujhosuR9197QQXwRWKywNvR3lsznq8bX+etn+Zto8yiuXmU+i3QFknJstFfpYGW/kORzM8QqX5qR+KfzIBd+EewBMJkfnzqi1yYg940PoTLNj35M8rbilNvG3ZDBtY+kEC57y3qjbV43jyO/TsjPGXIHPBgRhc/9ISqWDJuJwYkvmn7H3xuXdXL0NlHZX18HGftuVufjXPG/juaMnYn/I76Q/fCMdVPg72/oPA8x/PHGm3vDGy+8RLLQT4g3HdwNECJhU84D8MfFsC9yH+u27PfSg3nxjAg8CstqMC9fGpvfe9QqcBQMMWnI3KI4Lg8d3wR09j/rfYSMQ0qt285mUtKv7UhS2VNxQQshjNOnS9B9HKYgQcubZpRcMT1Q+3zyucMnx4DdqNWwtOV1hJpaapyCqssTcIzRfdXvoiBDSR49ZrFLO42TMBjpqG0XhbAiWKs7pHmxS5WJTif8Zi4lGUlAShy5t2MdT6QmNf9S7b4H07/PF4dk8AZf6sr5QA+7Q/BzEctc6hAIvba8Mvlr+xVXtYf72Gx0Xu6lltyeAJtV8ijhIsvjjPpMY2tt/NzqMi4csAS6RvU4Ey1TD9GGmxrUXUxosohMFiBox8uUI8M/QUzMYECGA9JO8ig99qSzM1GIrHBf657yzlYjafqwj1NpRkiMdY/9OF8E1j83mQBuXwyiZ9mC+bPXIKnmTuxgenrjinaPBxvdtO6S7TgXIw+l/6afwRkJq75bH9tQo6fUo1r/8EPXN/BSZit2mArhKQVZqoDkoL/VePDqI8lGaU/kljClPqdzKqwllbqY1+zxyhnobfIXeNFH0eZz2X6nJtfzDlkXzeg8p9rhTnazpg4zxbxq/p1Pd4FP0VaDAF1PRaRE03+4LxWOeF4VJTFckwCujTjNVDGa/8rYHjDFXyrthzqgQBfy2seMKh2f9ImuajkeA1EESTTByKaAvLWqM9a9cCcYcQ8SeMnAfx9R4Udyt12Ki+TLyjp1UWZw1i7dZ2/g2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mountebank-api
        name: api-mountebank-secret
        version: 0.1.0
      name: api-mountebank-secret
      namespace: mountebank

