apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-mountebank-secret
  namespace: mountebank
spec:
  encryptedData:
    secrets.toml: AgByK7nJjftPQeo/w36JYDvxVHrDaH/y8jLyMCQtRwvbiJlu/5YIFc9GlvTa0EagWBC6UBMpaUoD2FdHLGURQJKpKfoXJdBcfJ4+s+0KuLbS2iZdZdQBAfuvv15u6pXa/qXGkzeC7eAcaK2/AgmUOxWhDwfYAmvtAcFBhquvuut5HcFEMhzzsmSaqTX6/kNg/WSIxYerFv8pqfVxauG4zM+99U73rJmclf3ERrRnPQqhlZ02NvgpBJLOxZI8C94hlvfr/NksndMxKNCMdGyMQ4lj0szTdOa+itrLGmHGXwmnGRsfpaG5KbpsNNSMpkT78NDETW6Gfwl9Hs8hlQDt7Tm4YoIiGbPWaK9VTEa10UgZshZPrDyOJsAxMaJO1fdplHhQKWXe9bi8U0j9u9p8/ENLlGEk5rA4VG/vBSXmWe6zjHi73PELJaM5eNgk5Bk2rFPe5z0MGQh1XK7grenokUBxCvStmZfaAjNDvT/8BYSPfSYxKPM26leMqrULOXNXCIZ+k8yaJZjq/I3csyMH6/FNzOtr35sGG8xhlkC7A4dTqN3K6Ry1+aFgfCQ82fZGC20wOBq03OITmVs5+BDzRPo4MzeflMbfPLfrkViqKpKmQCkFeZFgR0x/a4UnkerAvwlX6Cd8DW0axcZAXQfkxIsi7b5mqhZZeq8XaleBrHjnA+lsiHJthTmPkEidvvkOW+5hhBWyMg5ZhrqTf/MwyfINd4WNQcaUuTTSGUZTR7NfYrficdEnfFja0JxqMa1hASqdSDmHo4aoeYdhPuiAF2UAQx4Q00nc0rxiGo9bFA4DgH9/RSaDkQegvGtxE43igkho2/qu+9bqMJag9LdcghPi2Y8x6hYCYW6LUJ551Xw3Df/VExGdrMuQvd7mAoIrWjqZRY3E9KEWV61g9g6nnJzC6EQRub2nrnxOEOqQutImFJsEVUIk1h+46IU2W0kzRUVtm5eGXvVte4CbKgnGDuqGl8Q8ESQWaQRS6wIHRA4zKn64Yy1Rh3+LqSu4QzfF3ttZ3oNndZRlpz6/+dT4UWNeOPifV2cGay0q8PoOjQA5LBTWPFfmMjW/ZNxhudc6zktYpaYLMzdX9RbA
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mountebank-api
        name: api-mountebank-secret
        version: 0.1.0
      name: api-mountebank-secret
      namespace: mountebank

