apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.16.1
    releaseName: istio-gateway
    namespace: istio-gateway
    includeCRDs: true