apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.5.2
    releaseName: sealed-secrets
    namespace: kube-system                  # kubeseal expects kube-system namespace, otherwise you'd have to use --controller-namespace in every command
    includeCRDs: true
    valuesFile: sealed-secrets-values.yaml
