---
# XXX: needed because kubeseal expects this name, otherwise you'll end up have to run 'kubeseal --controller-name sealed-secrets' every time
fullnameOverride: sealed-secrets-controller

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 500Mi
